# Generated by Django 5.2.17 on 2026-09-07 21:55

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0003_search_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recurrence', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('exact', 'تاریخ و ساعت دقیق')], max_length=8, verbose_name='نوع تکرار')),
                ('hour', models.PositiveSmallIntegerField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='ساعت')),
                ('minute', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='دقیقه')),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]), blank=True, default=list, size=None, verbose_name='روزهای هفته')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='روز ماه')),
                ('exact_date', models.DateField(blank=True, null=True, verbose_name='تاریخ')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='ideas.idea', verbose_name='ایده')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'یادآوری',
                'verbose_name_plural': 'یادآوری\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ReminderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField(verbose_name='زمان سررسید')),
                ('channel', models.CharField(choices=[('inapp', 'داخل سایت'), ('telegram', 'تلگرام')], max_length=10, verbose_name='کانال')),
                ('status', models.CharField(choices=[('pending', 'در حال ارسال'), ('sent', 'ارسال شد'), ('failed', 'ناموفق')], default='pending', max_length=8, verbose_name='وضعیت')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='reminders.reminder', verbose_name='یادآوری')),
            ],
            options={
                'verbose_name': 'ارسال یادآوری',
                'verbose_name_plural': 'ارسال\u200cهای یادآوری',
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['next_run_at'], name='reminder_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(('hour__gte', 0), ('hour__lte', 23)), name='reminder_hour_in_range'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(('minute__gte', 0), ('minute__lte', 59)), name='reminder_minute_in_range'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('day_of_month__isnull', True), ('exact_date__isnull', True), ('recurrence', 'daily')), models.Q(('day_of_month__isnull', True), ('exact_date__isnull', True), ('recurrence', 'weekly')), models.Q(('day_of_month__isnull', False), ('exact_date__isnull', True), ('recurrence', 'monthly')), models.Q(('day_of_month__isnull', True), ('exact_date__isnull', False), ('recurrence', 'exact')), _connector='OR'), name='reminder_parameters_match_recurrence'),
        ),
        migrations.AddConstraint(
            model_name='reminderdelivery',
            constraint=models.UniqueConstraint(fields=('reminder', 'scheduled_for', 'channel'), name='unique_reminder_delivery'),
        ),
    ]
