# Generated by Django 5.2.17 on 2026-09-07 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0003_search_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('reminder', 'یادآوری'), ('stale', 'ایدهٔ راکد'), ('telegram_capture', 'ثبت از تلگرام')], max_length=20, verbose_name='نوع')),
                ('text', models.TextField(verbose_name='متن')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده\u200cشده')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='ideas.idea', verbose_name='ایده')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(condition=models.Q(('is_read', False)), fields=['owner'], name='notification_unread_idx'), models.Index(fields=['owner', '-created_at'], name='notificatio_owner_i_75b535_idx')],
            },
        ),
    ]
