# Generated by Django 5.2.17 on 2026-09-08 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_search_columns'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notified_at', models.DateTimeField(verbose_name='زمان اطلاع')),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stale_alert', to='ideas.idea', verbose_name='ایده')),
            ],
            options={
                'verbose_name': 'هشدار ایدهٔ راکد',
                'verbose_name_plural': 'هشدارهای ایدهٔ راکد',
                'ordering': ['-notified_at'],
            },
        ),
    ]
