# Generated by Django 5.2.17 on 2026-09-26 14:11

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, upload_to=apps.users.models.avatar_upload_path, verbose_name='تصویر پروفایل'),
        ),
    ]
