# Generated by Django 5.2.17 on 2026-09-27 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('users', '0003_account_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='مرورگر')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('signed_in_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ورود')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین استفاده')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='sessions.session', verbose_name='نشست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دستگاه فعال',
                'verbose_name_plural': 'دستگاه\u200cهای فعال',
            },
        ),
    ]
