# Generated by Django 5.2.17 on 2026-09-07 20:57

import apps.ideas.content
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, verbose_name='نام')),
                ('color', models.CharField(choices=[('#3B82F6', 'آبی'), ('#8B5CF6', 'بنفش'), ('#06B6D4', 'فیروزه\u200cای'), ('#F472B6', 'صورتی'), ('#F59E0B', 'کهربایی'), ('#94A3B8', 'خاکستری'), ('#EF4444', 'قرمز'), ('#14B8A6', 'سبزآبی')], default='#3B82F6', max_length=7, verbose_name='رنگ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, verbose_name='نام')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.JSONField(default=apps.ideas.content.empty_document, verbose_name='محتوا')),
                ('plain_text', models.TextField(blank=True, verbose_name='متن ساده')),
                ('status', models.CharField(choices=[('idea', 'ایده'), ('planned', 'برنامه\u200cریزی\u200cشده'), ('doing', 'در حال انجام'), ('done', 'انجام\u200cشده'), ('archived', 'آرشیو')], default='idea', max_length=10, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('mid', 'متوسط'), ('high', 'زیاد')], default='mid', max_length=4, verbose_name='اولویت')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas', to='ideas.category', verbose_name='دسته')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='ideas', to='ideas.tag', verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name': 'ایده',
                'verbose_name_plural': 'ایده\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('name'), name='unique_category_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('name'), name='unique_tag_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['owner', 'status'], name='ideas_idea_owner_i_8b08ef_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['owner', '-updated_at'], name='ideas_idea_owner_i_49e459_idx'),
        ),
    ]
