# Generated by Django 5.2.17 on 2026-09-07 21:16

import apps.ideas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('image', 'عکس'), ('audio', 'صدا')], max_length=5, verbose_name='نوع')),
                ('file', models.FileField(upload_to=apps.ideas.models.attachment_upload_path, verbose_name='فایل')),
                ('thumbnail', models.FileField(blank=True, upload_to=apps.ideas.models.thumbnail_upload_path, verbose_name='بندانگشتی')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='نام اصلی')),
                ('content_type', models.CharField(max_length=100, verbose_name='نوع محتوا')),
                ('size_bytes', models.PositiveIntegerField(verbose_name='حجم')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت (میلی\u200cثانیه)')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ideas.idea', verbose_name='ایده')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیوست',
                'verbose_name_plural': 'پیوست\u200cها',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['idea', 'kind'], name='ideas_attac_idea_id_2278da_idx')],
            },
        ),
    ]
