# Generated by Django 5.2.17 on 2026-09-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_search_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان انتقال به سطل زباله'),
        ),
    ]
