# Generated by Django 5.2.17 on 2026-09-07 22:10

import apps.telegrambot.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=apps.telegrambot.models.generate_token, editable=False, max_length=64, unique=True, verbose_name='توکن')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان استفاده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_tokens', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'توکن اتصال تلگرام',
                'verbose_name_plural': 'توکن\u200cهای اتصال تلگرام',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='telegrambot_token_193f58_idx')],
            },
        ),
    ]
